和numpy的argmax几乎一样

In [2]:
import tensorflow as tf
import numpy as np

In [3]:

A=[[1,3,4,5,6]]
B = [[1,3,4],[2,4,1]]
C = [[1,3,4],[2,4,1],[100,33,44]]
with tf.Session() as sess:
	print(sess.run(tf.argmax(A,1)))
	print(sess.run(tf.argmax(B,1)))
	print(sess.run(tf.argmax(B)))
	print(sess.run(tf.argmax(C,0)))
	print(sess.run(tf.argmax(C,1)))
#	print(sess.run(tf.argmax(B,2)))




[4]
[2 1]
[1 1 0]
[2 2 2]
[2 1 0]


In [15]:
print(np.argmax(A))
print(np.argmax(B))
print(np.argmax(B,axis=1))
print(np.argmax(C))
print(np.argmax(C,0))
print(np.argmax(C,1))

4
2
[2 1]
6
[2 2 2]
[2 1 0]


In [6]:
with tf.Session() as sess:
# 	print(sess.run(tf.argmax([1,0,0],1)))#一个错误例子，别人教程里边瞎编的
	print(sess.run(tf.argmax([1,0,0],0)))


0
