广播操作
实际的Wx+b操作是广播操作
W*x + bias in batch condition

In [2]:

import tensorflow as tf
import numpy as np

In [1]:
#tensorflow add operation demo



#batch_size = 2
Wx = tf.constant([[100,200,300],[400,500,600]])
print(Wx.shape)
b = tf.constant([1,1,1])
print(b.shape)

#every vector in batch plus b
Wx_plus_b = Wx + b

with tf.Session() as sess:
    print(sess.run(Wx))
    print(sess.run(Wx_plus_b))

(2, 3)
(3,)
[[100 200 300]
 [400 500 600]]
[[101 201 301]
 [401 501 601]]


In [5]:
#模拟深度网络中的bias广播操作
a = tf.Variable(np.arange(12).reshape(3,4))
b = tf.constant([1,2,3,4],dtype=tf.int64)
#两种写法
bias_add1 = tf.nn.bias_add(a,b)
bias_add2 = a + b

#sess = tf.Session()
with tf.Session() as sess:
    tf.global_variables_initializer().run()

    print('a:\n',sess.run(a))
    print('bias_add1:\n',sess.run(bias_add1))
    print('bias_add2:\n',sess.run(bias_add2))


a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
bias_add1:
 [[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]
bias_add2:
 [[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]
