In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([[1.,2.,3.],[4.,5.,6.]])
x = tf.reshape(x,[1,2,3,1])

print(tf.Session().run(x))#变形成batch,行列2*3

[[[[ 1.]
   [ 2.]
   [ 3.]]

  [[ 4.]
   [ 5.]
   [ 6.]]]]


In [3]:
#valid_pad = tf.nn.conv2d(x, [1,2,2,1],[1,1,1,1], padding = 'VALID')
valid_pad = tf.nn.max_pool(x,[1,2,2,1],[1,2,2,1],padding = 'VALID')
same_pad = tf.nn.max_pool(x,[1,2,2,1],[1,2,2,1],padding='SAME')
same_pad2 = tf.nn.max_pool(x,[1,2,2,1],[1,1,2,1],padding='SAME')

In [10]:
print('valid:',valid_pad.get_shape())#不填充，行列全是stride2，输出行列1*1,舍一列
print('SAME:',same_pad.get_shape())#填充，输入2*3,stride2*2,输出行列1*2
print('SAME2:',same_pad2.get_shape())#填充，输入2*3,stride1*2,输出行列2*2
print('valid:',tf.Session().run(valid_pad))#舍一列，所以最大值5
print('same:',tf.Session().run(same_pad))
print('same(stride2):',tf.Session().run(same_pad2))

valid: (1, 1, 1, 1)
SAME: (1, 1, 2, 1)
SAME2: (1, 2, 2, 1)
valid: [[[[ 5.]]]]
same: [[[[ 5.]
   [ 6.]]]]
same(stride2): [[[[ 5.]
   [ 6.]]

  [[ 5.]
   [ 6.]]]]
