接口使用

In [1]:
import tensorflow as tf

In [2]:
t = tf.constant([1,2,3,4,5,6,7,8])
sess = tf.Session()
print(sess.run(t))

[1 2 3 4 5 6 7 8]


# 用strided_slice来切t，设定起点终点下标，左闭右开

In [3]:
t1 = tf.strided_slice(t,[1],[-1])
print(sess.run(t1))

[2 3 4 5 6 7]


In [15]:
#如果不用超大数值，左闭右开拿不到所有元素，t2“越界”写法可以拿到
t2 = tf.strided_slice(t,[3],[999])#stands for -0
print(sess.run(t2))
#负数不等于逆向，负数在下标界永远指倒数第几个
t22 = tf.strided_slice(t,[0],[-1])
print(sess.run(t22))

[4 5 6 7 8]
[1 2 3 4 5 6 7]


In [16]:
t3 = tf.strided_slice(t,[1],[3])
print(sess.run(t3))

[2 3]


[1 2 3 4 5 6 7]


# 加上stride

In [12]:

#t41 = tf.strided_slice(t,[0],[-1],[0])#must be non-zero
t42 = tf.strided_slice(t,[0],[-1],[1])
t43 = tf.strided_slice(t,[0],[-1],[2])
t44 = tf.strided_slice(t,[0],[-1],[3])
print(sess.run(t42))
print(sess.run(t43))
print(sess.run(t44))

[1 2 3 4 5 6 7]
[1 3 5 7]
[1 4 7]


In [9]:
t5 = tf.strided_slice(t,[3],[5])
print(sess.run(t5))

[4 5]


# 逆向，逆向加负数stride

In [14]:

t52 = tf.strided_slice(t,[5],[3])
t53 = tf.strided_slice(t,[5],[3],[-1])
t54 = tf.strided_slice(t,[5],[3],[1])
#print(sess.run(t41))
print(sess.run(t52))
print(sess.run(t53))
print(sess.run(t54))

[]
[6 5]
[]


# 更复杂的例子——三维，基本上每个维度分开控制

In [19]:
t = tf.constant([[[11, 12, 13], [21, 22, 23]],
                 [[31, 32, 33], [41, 42, 43]],
                 [[51, 52, 53], [61, 62, 63]]])
print(sess.run(t))

[[[11 12 13]
  [21 22 23]]

 [[31 32 33]
  [41 42 43]]

 [[51 52 53]
  [61 62 63]]]


In [20]:
#最外层1到2,锁定到31,32,33,41,42,43
#第二层0到1,锁定到31,32,33
#第三层0到3,锁定到31,32,33
t1 = tf.strided_slice(input_ = t,begin = [1,0,0], end = [2,1,3], strides = [1,1,1])
print(sess.run(t1))

[[[31 32 33]]]


In [21]:
#最外层1到2,锁定到31,32,33,41,42,43
#第二层-1到-3,stride-1,锁定41,42,43,31,32,33,
#第三层0到3,锁定全部
#注意最终顺序，因为第二层是逆序，所以4开头的那个list在3开头的list前边。
t2 = tf.strided_slice(t, [1, -1, 0], [2, -3, 3], [1, -1, 1])
print(sess.run(t2))

[[[41 42 43]
  [31 32 33]]]


In [22]:
#最外层1到2,锁定到31,32,33,41,42,43
#第二层-1到-3,stride-1,锁定41,42,43,31,32,33,
#第三层0到2,锁定局部，41,42,31,32
#注意最终顺序，因为第二层是逆序，所以4开头的那个list在3开头的list前边。
t22 = tf.strided_slice(t, [1, -1, 0], [2, -3, 2], [1, -1, 1])
print(sess.run(t22))

[[[41 42]
  [31 32]]]


In [23]:
#最外层1到1,无
t23 = tf.strided_slice(t, [1, -1, 0], [1, -3, 2], [1, -1, 1])
print(sess.run(t23))

[]


In [24]:
#最外层1到2,锁定到31,32,33,41,42,43
#第二层-1到-3,stride-1,锁定41,42,43,31,32,33,
#第三层0到3,锁定全部，但是stride=2，41,43,31,33
#注意最终顺序，因为第二层是逆序，所以4开头的那个list在3开头的list前边。
t24 = tf.strided_slice(t, [1, -1, 0], [2, -3, 3], [1, -1, 2])
print(sess.run(t24))

[[[41 43]
  [31 33]]]
