用来转换个图像什么的，不同接口可能使用的数据顺序不同。


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
input = tf.Variable(np.arange(12).reshape([2,3,2]))
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(input))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


# 原来的维度分别是0,1,2,拿来重新排序：

In [3]:
#本例，最外层不变，内部行列互换。
output_2 = tf.transpose(input,[0,2,1])
print(sess.run(output_2))

[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]]


In [4]:
#内外层颠倒：现在最内层是0和6,1和7等等
output_3 = tf.transpose(input,[2,1,0])
print(sess.run(output_3))

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [5]:
#也是把0和6的对应关系放在最内部。
output_4 = tf.transpose(input,[1,2,0])
print(sess.run(output_4))

[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]]
